from py4html import *

start()
heading("This is the begining of Page",1)
heading("without specifying heading number")
line_break()
heading("just trying",6)
paragraph("different implementations")
line_break()
division_begins()
heading("this comes inside the division",2)
heading("this too comes inside the division",3)
add_link("click this for info about links","https://www.w3schools.com/html/html_links.asp")
line_break()
add_link("click this for formatting information","https://www.w3schools.com/html/html_formatting.asp")
division_ends()
line_break()
biggest_heading("sreehari")
bigger_heading("sreehari")
big_heading("sreehari")
small_heading("sreehari")
smaller_heading("sreehari")
smallest_heading("sreehari")
heading("sruthi")
heading("sruthi",4,"bold")
heading("sruthi",3,"italics")
heading("sreehari",1,"italics")
heading("sreehari and his sruthi",1,"sub")
end()